import { Footer } from './_components/Footer';
import Header from './_components/Header';
import { AppProvider } from './_components/Providers';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppProvider>
          <Header />
          <div style={{ minHeight: '75vh' }}>{children}</div>
          <Footer />
        </AppProvider>
      </body>
    </html>
  );
}
