import { Footer } from './_components/Footer';
import Header from './_components/Header';
import { AppProvider } from './_components/Providers';
import './global.css';

export const metadata = {
  title: 'Welcome to web',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AppProvider>
      <Header />
      <body>{children}</body>
      <Footer />
    </AppProvider>
  );
}
